import 'package:uuid/uuid.dart';

const uuid = Uuid();

// Define an enumeration named Category to represent various expense categories.
// Enumeration values representing different categories
enum Category { food, travel, outing, work }

class Expense {
  Expense(
      {required this.title,
      required this.amount,
      required this.date,
      required this.category})
      // Initialize the id property with a unique value generated by uuid.v4()
      : id = uuid.v4();

  final String id;
  final String title;
  final double amount;
  final DateTime date;
  final Category category;
}
